// api.ts exports Zod schemas used by backend routes (body parsers, query params, responses)
// types/ exports individual TypeScript type files generated by orval
// Both export some names identically — TypeScript 5 raises TS2728 on duplicate exports.
// Solution: re-export from api.ts first (source of truth for schemas), then
// re-export from types/ only the names NOT already in api.ts.
export * from "./generated/api";

import * as apiExports from "./generated/api";
import * as typeExports from "./generated/types";

// Re-export from types/ only the names that don't overlap with api.ts exports
type ExportedNames = keyof typeof apiExports;
for (const key of Object.keys(typeExports) as (keyof typeof typeExports)[]) {
  if (!(key in apiExports)) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (globalThis as any)[key] = typeExports[key];
  }
}
